{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adguard.trusttunnel",
    "module": "trusttunnel-client-android",
    "version": "1.3.0-alpha.1-5-g1fc85997",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "trusttunnel-client-android-1.3.0-alpha.1-5-g1fc85997.aar",
          "url": "trusttunnel-client-android-1.3.0-alpha.1-5-g1fc85997.aar",
          "size": 16700636,
          "sha512": "68485e0f8873a04c3f04b9ce702fabc0fc2dd98895eedb586b3d040abe0599466f07c8006d1c9350c357e13dc3eaf5f6f2318b8d7c1b8420787462d03c0e9358",
          "sha256": "979e90530d4a3c284788f49af044d6e6526fd92d7228be92479ed52c6bad3a6d",
          "sha1": "6d1df2073466af19b381db6c8cfd815c05a79634",
          "md5": "20eb46fb794e5d2fecfc7236465e5893"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "logback-android",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "trusttunnel-client-android-1.3.0-alpha.1-5-g1fc85997.aar",
          "url": "trusttunnel-client-android-1.3.0-alpha.1-5-g1fc85997.aar",
          "size": 16700636,
          "sha512": "68485e0f8873a04c3f04b9ce702fabc0fc2dd98895eedb586b3d040abe0599466f07c8006d1c9350c357e13dc3eaf5f6f2318b8d7c1b8420787462d03c0e9358",
          "sha256": "979e90530d4a3c284788f49af044d6e6526fd92d7228be92479ed52c6bad3a6d",
          "sha1": "6d1df2073466af19b381db6c8cfd815c05a79634",
          "md5": "20eb46fb794e5d2fecfc7236465e5893"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "trusttunnel-client-android-1.3.0-alpha.1-5-g1fc85997-sources.jar",
          "url": "trusttunnel-client-android-1.3.0-alpha.1-5-g1fc85997-sources.jar",
          "size": 44141,
          "sha512": "52574ea8efd90172b7a92c0029469d838e9c73a6e407326feda21e6ee44e4c9482dd9b57b01cbc7dec7388ee804ef36907e3527b994ff8a63cb30aee315bd08f",
          "sha256": "cf154f6f01d400f39de8f2479abc5cd6d9ecfa46b33752de856aa28b3ef3b65a",
          "sha1": "3fbb642209347b091a074e33dd82da0c5333e806",
          "md5": "4121e84aceadaa8e1dcb9b859a3f506e"
        }
      ]
    }
  ]
}
