{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adguard.trusttunnel",
    "module": "trusttunnel-client-android",
    "version": "1.1.5-rc.6-2-g9e7e6bb6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "trusttunnel-client-android-1.1.5-rc.6-2-g9e7e6bb6.aar",
          "url": "trusttunnel-client-android-1.1.5-rc.6-2-g9e7e6bb6.aar",
          "size": 16206575,
          "sha512": "cfd0db09b221d0d21281fa5d36b8217d34dce6191ca781f022abc6fb6d562702f7826c13eb6a8dba0f379f35c1d3667a62d856a3bd9971d6d4ef0edd19c543c8",
          "sha256": "b72e28615a3a149a012190ab8cc1eda8c2c37d9c1afd172da70df333610f64f4",
          "sha1": "93030dc6d45c3803366cdd3f968f881ab14c7474",
          "md5": "144a377214d7e0431713f08eb6a230c2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "logback-android",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "trusttunnel-client-android-1.1.5-rc.6-2-g9e7e6bb6.aar",
          "url": "trusttunnel-client-android-1.1.5-rc.6-2-g9e7e6bb6.aar",
          "size": 16206575,
          "sha512": "cfd0db09b221d0d21281fa5d36b8217d34dce6191ca781f022abc6fb6d562702f7826c13eb6a8dba0f379f35c1d3667a62d856a3bd9971d6d4ef0edd19c543c8",
          "sha256": "b72e28615a3a149a012190ab8cc1eda8c2c37d9c1afd172da70df333610f64f4",
          "sha1": "93030dc6d45c3803366cdd3f968f881ab14c7474",
          "md5": "144a377214d7e0431713f08eb6a230c2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "trusttunnel-client-android-1.1.5-rc.6-2-g9e7e6bb6-sources.jar",
          "url": "trusttunnel-client-android-1.1.5-rc.6-2-g9e7e6bb6-sources.jar",
          "size": 44141,
          "sha512": "52574ea8efd90172b7a92c0029469d838e9c73a6e407326feda21e6ee44e4c9482dd9b57b01cbc7dec7388ee804ef36907e3527b994ff8a63cb30aee315bd08f",
          "sha256": "cf154f6f01d400f39de8f2479abc5cd6d9ecfa46b33752de856aa28b3ef3b65a",
          "sha1": "3fbb642209347b091a074e33dd82da0c5333e806",
          "md5": "4121e84aceadaa8e1dcb9b859a3f506e"
        }
      ]
    }
  ]
}
